services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  backend:
      container_name: backend-vueNuxt
      build: './backend'
      volumes:
        - './backend:/app'
        - '/app/node_modules'
      tty: true
      ports:
        - '8080:8080'
      environment:
        - CHOKIDAR_USEPOLLING=true
        - WATCHPACK_POLLING=true
        - TZ=Asia/Bangkok
      depends_on:
      - mongo
  frontend:
    container_name: frontend-vueNuxt
    build: './frontend'
    volumes:
      - './frontend/:/app'
      - '/app/node_modules'
    tty: true
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - TZ=Asia/Bangkok
    depends_on:
      - mongo
      - backend